Add using gem5 to generate BBV function for all cases

diff --git a/runspec_gem5_power/999.specrand_ir/Makefile b/runspec_gem5_power/999.specrand_ir/Makefile
--- a/runspec_gem5_power/999.specrand_ir/Makefile
+++ b/runspec_gem5_power/999.specrand_ir/Makefile
@@ -11,7 +11,7 @@ host: $(EXECUTABLE)
 gem5: $(EXECUTABLE)
 	$(TIMEG) $(GEM5) $(GEM5_OPT) $(GEM5_PY) -c $(EXECUTABLE) -o " $(ARGS)" $(GEM5_PY_OPT) >>../consume_time.log 2>&1
 	@chmod -x *gem5.log
-	@grep -nr "^Error" stderr_gem5.log && echo $$(basename $(BENCH_PATH)) >> ../fail_gem5_crash.log ; true
+	@grep -nr "^Error" stderr_gem5.log && echo $$(basename $(BENCH_PATH)) >> ../fail_gem5_crash.log; true
 
 $(EXECUTABLE):
 	ln -s $(BENCH_PATH)/exe/$(EXECUTABLE)
@@ -27,7 +27,7 @@ objdump: $(EXECUTABLE)
 diff:
 	@diff host_out.log gem5_out.log >/dev/null 2>&1 \
 		&& echo $$(basename $(BENCH_PATH)) DIFF PASSED \
-		|| echo $$(basename $(BENCH_PATH)) DIFF FAILED | tee -a ../fail_gem5_diff.log ; true
+		|| echo $$(basename $(BENCH_PATH)) DIFF FAILED | tee -a ../fail_gem5_diff.log; true
 
 ls:
 	find -maxdepth 1 -type f -exec ls -lFh {} \+
@@ -45,14 +45,14 @@ checkpoints: $(EXECUTABLE)
 	$(TIMEH) $(GEM5) $(GEM5_PY) --take-simpoint-checkpoints=$(FILE).simpts,$(FILE).weights,$(INTERVAL_SIZE),$(WARMUP_LENGTH) -c $(EXECUTABLE) -o " $(ARGS)" --mem-size=16384MB >$(FILE)_checkpoints.log 2>&1
 	@cat $(FILE)_checkpoints.log >> $(FILE)_trace.log
 	@echo ---------------------cpts handle $(FILE) Finished ---------------------->>$(FILE)_trace.log
-	@-grep -niE "FAIL|ERR|FAULT" $(FILE)_trace.log >> $(FILE)_trace_err.log ; true
+	@-grep -niE "FAIL|ERR|FAULT" $(FILE)_trace.log >> $(FILE)_trace_err.log; true
 
 restore: $(EXECUTABLE)
 	@echo ---------------------rscpt handle $(FILE) beginning ---------------------->>$(FILE)_trace.log
 	$(TIMEH) $(GEM5) -d ./output_ckp$(NUM_CKP) $(GEM5_PY) --restore-simpoint-checkpoint -r $(NUM_CKP) --checkpoint-dir ./m5out -c $(EXECUTABLE) -o " $(ARGS)" --cpu-type=$(CPU_TYPE) $(CACHE_OPT) >$(FILE)_restore.log 2>&1
 	@cat $(FILE)_restore.log >> $(FILE)_trace.log
 	@echo ---------------------rscpt handle $(FILE) Finished ---------------------->>$(FILE)_trace.log
-	@-grep -niE "FAIL|ERR|FAULT" $(FILE)_trace.log >> $(FILE)_trace_err.log ; true
+	@-grep -niE "FAIL|ERR|FAULT" $(FILE)_trace.log >> $(FILE)_trace_err.log; true
 
 gem5_pipeview: $(EXECUTABLE)
 	@echo ---------------------gem5pv handle $(FILE) beginning ---------------------->>$(FILE)_trace.log
@@ -72,14 +72,26 @@ restore-all: $(EXECUTABLE)
 	@rm -rf ./$(FILE)_RS_NUM.log;
 	@m=(`awk 'END {print NR}' ./$(FILE).merge`);\
 	exec 6<>$(FLOODGATE);\
-	for i in `seq $${m}`; do read -u6; ( \
-		$(TIMEH) $(GEM5) -d ./output_ckp$${i} $(GEM5_PY) --restore-simpoint-checkpoint -r $${i} --checkpoint-dir ./m5out -c $(EXECUTABLE) -o " $(ARGS)" --cpu-type=$(CPU_TYPE) $(CACHE_OPT) >$(FILE)_restore.log 2>&1; \
-		cat $(FILE)_restore.log >> $(FILE)_trace.log; \
-		grep -niE "FAIL|ERR|FAULT" $(FILE)_trace.log >> $(FILE)_trace_err.log ; true ;\
-		weights=`sed -n "$${i}p" $(FILE).merge | awk '{print $$3}' `; \
+	for i in `seq $${m}`; do read -u6; (\
+		$(TIMEH) $(GEM5) -d ./output_ckp$${i} $(GEM5_PY) --restore-simpoint-checkpoint -r $${i} --checkpoint-dir ./m5out -c $(EXECUTABLE) -o " $(ARGS)" --cpu-type=$(CPU_TYPE) $(CACHE_OPT) >$(FILE)_restore.log 2>&1;\
+		cat $(FILE)_restore.log >> $(FILE)_trace.log;\
+		grep -niE "FAIL|ERR|FAULT" $(FILE)_trace.log >> $(FILE)_trace_err.log; true;\
+		weights=`sed -n "$${i}p" $(FILE).merge | awk '{print $$3}'`;\
 		cpi=`grep "system.switch_cpus.totalCpi.*" ./output_ckp$${i}/stats.txt | awk 'END{print $$2}'`;\
 		echo ckp$${i} $${weights} $${cpi} >> ./$(FILE)_CKPS_CPI.log;\
 		echo Finshed_Restore_CKP_$${i} >> ./$(FILE)_RS_NUM.log;\
   		echo >&6 )& \
 	done;
 	@echo ---------------------rscpt_all handle $(FILE) Finished ---------------------->>$(FILE)_trace.log
+
+simpoint: $(EXECUTABLE)
+	@echo ---------------------bbv_simpt handle $(FILE) beginning ---------------------->>$(FILE)_trace.log
+	@$(TIMEH) $(GEM5) --outdir=$(FILE)_bbv $(GEM5_PY) --simpoint-profile --simpoint-interval=$(INTERVAL_SIZE) -c $(EXECUTABLE) -o " $(ARGS)" --cpu-type=NonCachingSimpleCPU --mem-size=16384MB >$(FILE)_gem5_bbv.log 2>&1;\
+	gunzip -c ./$(FILE)_bbv/simpoint.bb.gz >./$(FILE)_bbv/simpoint.bb;\
+	MAXK=`wc -l ./$(FILE)_bbv/simpoint.bb | awk 'END{print sqrt($$1)}'`;\
+	$(SIMPOINT_EXE) -loadFVFile ./$(FILE)_bbv/simpoint.bb.gz -maxK $${MAXK} -saveSimpoints ./$(FILE).simpts -saveSimpointWeights ./$(FILE).weights -inputVectorsGzipped >$(FILE)_simpoint.log 2>&1;\
+	#$(SIMPOINT_EXE) -loadFVFile $(FILE).bb.out -maxK $(MAXK) -saveSimpoints ./$(FILE).simpts -saveSimpointWeights ./$(FILE).weights >>$(FILE)_trace.log 2>&1 ; \
+	paste $(FILE).simpts $(FILE).weights | awk '{printf "%-20d %-20d %-15.5f\n",$$2,$$1,$$3}' 1>$(FILE).merge;\
+	sort $(FILE).merge -n -k 2 -o $(FILE).merge
+	@echo ---------------------bbv_simpt handle $(FILE) Finished ---------------------->>$(FILE)_trace.log
+	@-grep -niE "FAIL|ERR|FAULT" $(FILE)_trace.log >> $(FILE)_trace_err.log; true
